### ISSUE TITLE
Well, there is something weird, the script stops

### ISSUE THREAD

**Issue by chris-blues** [chris-blues/Nasa2FGearthview#3]
> Well, there is something weird, the script started with
> 
> ./convert.sh download world clouds heights 16k
> 
> stops at:
> 
> ```
> ########################
> ## Resize nightlights ##
> ########################
> 
> No suitable image found. Using NASA original...
> Resize/Image/tmp[nightlights_54000x27000.mpc]: 96767 of 96768, 100% complete.
> ```
> 
> And if I start it again, it goes on with the rest of leveling etc.. It is not obvious to me why it stops there, I'll inquire a bit more.

_Originally posted by @dirteat in https://github.com/chris-blues/Nasa2FGearthview/issues/1#issuecomment-477782745_

(this issue is about v0.13)

**Comment by chris-blues** [comment]
So it is done resizing the 54000x27000 map. Did it crash, like you're back at the prompt, or did it just stop showing any progress?

Using 'gkrellm', you can watch the disk activity. Maybe it was just choking writing all that data. That happens on my machine a lot. If I wait a long while, it eventually will continue working...
If it crashes, then there is something weird going on. Maybe 'dmesg' might show something interesting...

**Comment by dirteat** [comment]
You're right, I think it is hardware failures, dmesg show some errors with my filesystem, which is indeed on a SSD. I'll try on another machine/disk to confirm!

**Comment by chris-blues** [comment]
OK, let me know, what you find and good luck with your SSD! Hope it won't go to /dev/null...

**Comment by dirteat** [comment]
Ok, did not find any problem, generation of 16k images is long and indeed requires more than 300GB, but it works. Closing...

**Comment by chris-blues** [comment]
:thumbsup:
