### ISSUE TITLE
ImageMagick-7 and alpha channel

### ISSUE THREAD

**Issue by eatdust** [chris-blues/Nasa2FGearthview#4]
Hi Chris,
I've just pushed some changes to fix two things:

- normalmap binary is no longer compiling against ImageMagick-7, so I have forked the project and fix it there: https://github.com/eatdust/normalmap
I've reflected the change within the README and convert.sh

- The script was not providing an alpha channel, and, actually, Earthview can use it. So, I added some change to normalmap to do so (it seems that Earthview uses inverse height as alpha channel).

- I've added some possibility to change the resizing method (and memory limits which were quite low). I am currently testing is -distort Resize gives really better results.

Feel free to pass over my changes!
Cheers,
the other Chris.

**Comment by chris-blues** [comment]
Hi Chris!

Very nice! About the low limits: I put these in, so that at the early stages of processing these huge images are not going into RAM in any way but stay swapped. Otherwise  there's (was) a danger that ImageMagick would run out of memory and abort. So I forced IM to work directly on disk... I'm not sure if it's still neccessary.

About the alpha channel. Yes I saw your discussion on the forums. But had nothing to add. I neither remembered adding an alpha channel to the normalmaps, nor do I remember how we did this and why... So... I checked my local backups and found all my normalmaps without an alpha channel... Didin't want to add the confusion.

Anyway, thanks a lot for improving on the script! Did you also push the changes to FGMeta?

Cheers

**Comment by eatdust** [comment]
>  Did you also push the changes to FGMeta?

I have not commit rights on FG, so maybe I can let you do it? For the RAM, it seems to work fine, I think I put 512MiB as default now, and as far as I see on my computer, at least with convert from ImageMagick-7, it does not exceed this.

I am currently testing the a full distort option, it is like crazy long, but I would like to check the result on the 16k world maps to see if that is worth doing :)

**Comment by eatdust** [comment]
> I checked my local backups and found all my normalmaps without an alpha channel

Ok, good to know, so these should work, at least for the shadowing effects.

That's weird though, because I downloaded the torrent a while ago, the one named "Earthview - complete", and in this one, normalmap_earth_N1.png for instance has an alpha channel (I spotted it with gimp)

**Comment by chris-blues** [comment]
Yes the new normalmaps generated by the script do add an empty alpha channel. But the ones I generated before that had no alpha channel. But maybe I lost the originals over time... I don't know really.

**Comment by chris-blues** [comment]
> > Did you also push the changes to FGMeta?
> 
> I have not commit rights on FG, so maybe I can let you do it?

No problem. Are you ready for a release or do you still want to have some time to check it out?

**Comment by eatdust** [comment]
You can go for a release then! No needs to wait for my tests, they'll be minor improvements at best.

**Comment by eatdust** [comment]
Let's close then!

**Comment by chris-blues** [comment]
*thumbsup*

**Comment by eatdust** [comment]
Arg, I think there is an issue with ImageMagick-7, not related to my changes, but the definition of the alpha channel has changed, it looks like some call to "convert" in the script are affected, especially for the clouds. So wait a bit before pushing to fgdata then.

From https://imagemagick.org/script/porting.php

> We support alpha rather than opacity (0 transparent; QuantumRange opaque).

and also:

>the default is to update the RGBA channels, previously, in IMv6, the default was RGB. If you get results that differ from IMv6, you may need to specify -channel RGB...

**Comment by chris-blues** [comment]
Nice catch! I'll ~~remove~~ rename the release...

**Comment by eatdust** [comment]
Ok, I've pushed two commits, one is for cosmetics, but please review the latest one. I've tested and that seems to work. Note the addition of \! in two calls, dunno if you did not put it on purpose, so please check.

I am currently unable to test if the -distort Resize gives better results, it is currently bugged in ImageMagick-7 currently (reported here):
https://github.com/ImageMagick/ImageMagick/issues/1839

Closing then, reopen if you see a problem!
Thanks!

**Comment by chris-blues** [comment]
Hm, trying to test your improvements, I can't build your normalmap binary:
I'm on Debian 10, with libmagickcore-6.q16-dev installed.

```$ ./waf configure build
Setting top to                           : Earthview/normalmap-master 
Setting out to                           : Earthview/normalmap-master/build 
Checking for 'gcc' (c compiler)          : /usr/bin/gcc 
Checking for program pkg-config          : /usr/bin/pkg-config 
Checking for 'MagickCore'                : yes 
'configure' finished successfully (0.048s)
Waf: Entering directory `Earthview/normalmap-master/build'
[1/3] c: src/normalmap.c -> build/src/normalmap.c.1.o
[2/3] c: src/main.c -> build/src/main.c.1.o
In file included from ../src/main.c:25:
../src/normalmap.h:22:10: fatal error: MagickCore/MagickCore.h: Datei oder Verzeichnis nicht gefunden
 #include <MagickCore/MagickCore.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from ../src/normalmap.c:26:
../src/normalmap.h:22:10: fatal error: MagickCore/MagickCore.h: Datei oder Verzeichnis nicht gefunden
 #include <MagickCore/MagickCore.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Waf: Leaving directory `Earthview/normalmap-master/build'
Build failed
 -> task in 'normalmap' failed (exit status 1): 
        {task 139905305512080: c main.c -> main.c.1.o}
['/usr/bin/gcc', '-std=c11', '-fopenmp', '-I/Earthview/normalmap-master/build/src', '-I/Earthview/normalmap-master/src', '-I/usr/include/x86_64-linux-gnu/ImageMagick-6', '-I/usr/include/ImageMagick-6', '-DHAVE_MAGICK_CORE=1', '-DMAGICKCORE_HDRI_ENABLE=0', '-DMAGICKCORE_QUANTUM_DEPTH=16', '../src/main.c', '-c', '-o', 'src/main.c.1.o']
 -> task in 'normalmap' failed (exit status 1): 
        {task 139905305510992: c normalmap.c -> normalmap.c.1.o}
['/usr/bin/gcc', '-std=c11', '-fopenmp', '-I/Earthview/normalmap-master/build/src', '-I/Earthview/normalmap-master/src', '-I/usr/include/x86_64-linux-gnu/ImageMagick-6', '-I/usr/include/ImageMagick-6', '-DHAVE_MAGICK_CORE=1', '-DMAGICKCORE_HDRI_ENABLE=0', '-DMAGICKCORE_QUANTUM_DEPTH=16', '../src/normalmap.c', '-c', '-o', 'src/normalmap.c.1.o']```

**Comment by chris-blues** [comment]
Just came to think about it and this all started that normalmap was not compiling (or rather: not working correctly) against imageMagick7. Since I only have IM6 I'll use the old normalmap from planrich, that should work. Right?

So we'll need to build a switch for the message, if we have IM6 use planrich's NM, if IM7 use your fork.

**Comment by eatdust** [comment]
Ah yes! The problem is that if you use planrich/normalmap you won't get the possibility to add the alpha channel to the normalmaps, it is hard-coded to none in the source code.

In my fork, I've fixed both the API and added the alpha channel option, I guess it makes sense to support only imagemagick-7 at that point, especially knowing that planrich did not touch the code or answer issues in the last few years.

Nonetheless, as a hack, you can force planrich/normalmap to add ALPHA_INVERSE_HEIGHT, look at main.c in the structure nmapvals! But then you need to remove the option -a in the convert.sh script as it does not exist for planrich/normalmap.

Hope it is ok!
Cheers.

**Comment by chris-blues** [comment]
In general, I'd like to keep the script working for all users. Since Debian10 is gonna be around for a long time, I would think it's more convenient to provide users with the possibility to build an almost complete set of textures, than to leave them without any normalmaps at all.
Maybe in normalmap there's a possibility to check for the installed version of IM? Unfortunately I didn't touch any C/C++ since more than 20 years, so I'm no help there...

**Comment by dirteat** [comment]
Yep, the script itself is fine, but I would need to fix normalmap binary. Since I've forked it, that is definitely doable, I'll certainly do some conditionals on defined variables like -DMAGICK6 or something like that to compile against magick6 while still allowing passing the alpha channel.

**Comment by chris-blues** [comment]
Nice!

I keep thinking about scripting the compilation, since it's a bit tricky to compile the normalmap. I couldn't find any hint, where to find the correct waf to use. I borrowed [one ready-to-use file from ardour](https://github.com/Ardour/ardour/blob/master/waf), since they use it also and have a copy of it in their repo. And it worked fine, so I didn't spend another thought. I'm thinking about doing the same as ardour, just copy the file as-is.

What do you think?

**Comment by eatdust** [comment]
If I remember waf, that's like autotools, you can generate all the scripts required to be a self-contained compiling python package, I'll have a look too!

**Comment by eatdust** [comment]
Ok, got some time tonight, done.

1) Default remains to compile normalmap against imagemagick7, the API6 is only in maintenance mode.
2) To compile against imagemagick6, just append --oldmagick during the waf configure.
3) I've added the waf script in the package, so doing

./waf configure --oldmagick
./waf build
should get you done. Let me know if that does not work.

NB: The changes made on the convert.sh script to support the call to magick7/convert binary are compatible with magick6/convert. The convert.sh script should then work with all versions of imagemagick. Just normalmap should be pulled from my repos, and eventually configured with --oldmagick for imagemagick <= 6.

**Comment by chris-blues** [comment]
That was quick! Nice!

I was just trying to open an issue on normalmap, but the button is missing... Maybe some repo setting?

Anyway, here's what I wanted to report:

> Now, after `./waf configure --oldmagick` it says
> ```
> Checking for program 'pkg-config' : not found
> Could not find the program ['pkg-config']
> ```

Maybe another addition to your readme? :o)

I'll try to model through and will report any findings...

_Solved by installing pkg-config via apt._

**Comment by chris-blues** [comment]
```
Checking for 'MagickCore'                : not found 
The configuration failed
```
With Richards NM it finds the MagickCore. Probably some path thing... _no idea how to fix that... roadblock_

**Comment by eatdust** [comment]
Ok, I've added an issue button :)
For the MagickCore issue, that is very weird, I did not touch that part of the code. The devel files of ImageMagic6 comes with a file named MagickCore.pc that is found by pkg-config. On my machine, it is there: /usr/lib64/pkgconfig/MagickCore.pc and should be found by the script.
Could you check that this file is installed?

**Comment by chris-blues** [comment]
No such file on my system.

Lets move this discussion to your repo... [done](https://github.com/eatdust/normalmap/issues/1#issue-557562228)
